spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moraesfood
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

